global_obj.data.navPos = "3";
tpl.developer_insite = [
'<!--{ include file="header.tpl" }-->',
	tpl.header,
'<link href="http://mat1.gtimg.com/app/opent/css/developer/index/developer.css" rel="stylesheet" type="text/css"/>',
'<div class="wrapper developer_insite">', 
	'<h1>站内应用</h1>',
	'<p>接入微博应用频道，用户可直接在微博内访问使用；</p>',
	'<p>深度整合微博众多推广资源及传播渠道，获得更多的曝光度；</p>',
	'<p>可接入腾讯托管及支付服务，托管服务器提供免费试用。</p>',
	'<div class="developer_mask">',
		'<a href="/developer/web/" title="网页应用" class="developer_mask_link">网页应用&gt;</a>',
	'</div>',
	'<a href="javascript:void(0);" title="创建应用" class="developer_newapp"></a>',
'</div>',
'<div class="wrapper developer_interfix">',
	'<div class="developer_doc">',
		'<h3 class="developer_subtit">文档说明</h3>',
		'<ul class="developer_doc_list doc_icons_insite">',
			'<li class="developer_doc_li developer_doc_li1">',
				'<h4><a href="http://wiki.open.t.qq.com/index.php/%E5%BA%94%E7%94%A8%E6%8E%A5%E5%85%A5%E6%8C%87%E5%BC%95" target="_blank">接入指引</a></h4>',
				'<p>从创建应用到应用通过审核的流程介绍</p>',
			'</li>',
			'<li class="developer_doc_li developer_doc_li2">',
				'<h4><a href="http://wiki.open.t.qq.com/index.php/API%E6%96%87%E6%A1%A3" target="_blank">API文档</a></h4>',
				'<p>API接口描述及说明文档</p>',
			'</li>',
			'<li class="developer_doc_li developer_doc_li3">',
				'<h4><a href="http://wiki.open.t.qq.com/index.php/%E8%85%BE%E8%AE%AF%E5%BE%AE%E5%8D%9A%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0%E7%AC%AC%E4%B8%89%E6%96%B9%E5%BA%94%E7%94%A8%E5%AE%A1%E6%A0%B8%E8%A7%84%E8%8C%83" target="_blank">审核规范</a></h4>',
				'<p>腾讯微博开放平台第三方应用审核规范</p>',
			'</li>',
			'<li class="developer_doc_li developer_doc_li4">',
				'<h4><a href="http://wiki.open.t.qq.com/index.php/%E5%BA%94%E7%94%A8%E9%A2%91%E9%81%93%E6%8E%A5%E5%85%A5%E6%8C%87%E5%BC%95" target="_blank">应用频道</a></h4>',
				'<p>站内应用接入微博应用频道指引</p>',
			'</li>',
		'</ul>',
	'</div>',
	'<div class="developer_apps">',
		'<h3 class="developer_subtit">成功案例</h3>',
		'<ul class="developer_applist">',
			'<li class="demo_app">',
				'<a target="_blank" href="http://app.t.qq.com/app/intro/801215590?via=801215590_WB.MYAPPS.1.14" class="demo_app_icon">',
					'<img src="http://openmat.gtimg.com/pic/801215590_50.png" class="demo_app_icon_img"/>',
				'</a>',
				'<h3>',
					'<a target="_blank" href="http://app.t.qq.com/app/intro/801215590?via=801215590_WB.MYAPPS.1.14" title="字幕帝">字幕帝</a>',
				'</h3>',
			'</li>',
			'<li class="demo_app">',
				'<a target="_blank" href="http://app.t.qq.com/app/intro/801210285?via=801210285_WB.MYAPPS.1.14" class="demo_app_icon">',
					'<img src="http://openmat.gtimg.com/pic/801210285_50.png" class="demo_app_icon_img"/>',
				'</a>',
				'<h3>',
					'<a target="_blank" href="http://app.t.qq.com/app/intro/801210285?via=801210285_WB.MYAPPS.1.14" title="八卦神器">八卦神器</a>',
				'</h3>',
			'</li>',
			'<li class="demo_app">',
				'<a target="_blank" href="http://app.t.qq.com/app/intro/801326013?via=801326013_WB.MYAPPS.1.14" class="demo_app_icon">',
					'<img src="http://openmat.gtimg.com/pic/801326013_50.png" class="demo_app_icon_img"/>',
				'</a>',
				'<h3>',
					'<a target="_blank" href="http://app.t.qq.com/app/intro/801326013?via=801326013_WB.MYAPPS.1.14" title="愚人大整蛊">愚人大整蛊</a>',
				'</h3>',
			'</li>',
			'<li class="demo_app">',
				'<a target="_blank" href="http://app.t.qq.com/app/intro/801254428?via=801254428_WB.MYAPPS.1.14" class="demo_app_icon">',
					'<img src="http://openmat.gtimg.com/pic/801254428_50.png" class="demo_app_icon_img"/>',
				'</a>',
				'<h3>',
					'<a target="_blank" href="http://app.t.qq.com/app/intro/801254428?via=801254428_WB.MYAPPS.1.14" title="漫画君">漫画君</a>',
				'</h3>',
			'</li>',
			'<li class="demo_app">',
				'<a target="_blank" href="http://app.t.qq.com/app/intro/23026?via=23026_WB.MYAPPS.1.14" class="demo_app_icon">',
					'<img src="http://openmat.gtimg.com/pic/23026_50.png" class="demo_app_icon_img"/>',
				'</a>',
				'<h3>',
					'<a target="_blank" href="http://app.t.qq.com/app/intro/23026?via=23026_WB.MYAPPS.1.14" title="博雅-斗地主">博雅-斗地主</a>',
				'</h3>',
			'</li>',
			'<li class="demo_app">',
				'<a target="_blank" href="http://app.t.qq.com/app/intro/23006?via=23006_WB.MYAPPS.1.14" class="demo_app_icon">',
					'<img src="http://openmat.gtimg.com/pic/23006_50.png" class="demo_app_icon_img"/>',
				'</a>',
				'<h3>',
					'<a target="_blank" href="http://app.t.qq.com/app/intro/23006?via=23006_WB.MYAPPS.1.14" title="德克萨斯扑克">德克萨斯扑克</a>',
				'</h3>',
			'</li>',
			'<li class="demo_app">',
				'<a target="_blank" href="http://app.t.qq.com/app/intro/100619194?via=100619194_WB.MYAPPS.1.14" class="demo_app_icon">',
					'<img src="http://openmat.gtimg.com/pic/100619194_50.png" class="demo_app_icon_img"/>',
				'</a>',
				'<h3>',
					'<a target="_blank" href="http://app.t.qq.com/app/intro/100619194?via=100619194_WB.MYAPPS.1.14" title="你画我猜">你画我猜</a>',
				'</h3>',
			'</li>',
			'<li class="demo_app">',
				'<a target="_blank" href="http://app.t.qq.com/app/intro/23025?via=23025_WB.MYAPPS.1.14" class="demo_app_icon">',
					'<img src="http://openmat.gtimg.com/pic/23025_50.png" class="demo_app_icon_img"/>',
				'</a>',
				'<h3>',
					'<a target="_blank" href="http://app.t.qq.com/app/intro/23025?via=23025_WB.MYAPPS.1.14" title="美式八球">美式八球</a>',
				'</h3>',
			'</li>',
		'</ul>',
	'</div>',
'</div>',
'<!--{ include file="footer.tpl" }-->',
		tpl.footer
	].join("");
	$('#main').html(tmpl(tpl.developer_insite,global_obj.data));
	window.init();
	util.setLoginInfo();
	$(".developer_newapp").click(function(){
		if( hdlogin==undefined || hdlogin == false || hdlogin == 'false' ){
			return checkuserLogin(encodeURIComponent(location.href.replace(new RegExp(location.pathname+".*"),"/apps/add/4")));
		}else{
			if( userInfo.reg_wb == 0 ){
				location.href = "http://reg.t.qq.com/invite.php";
				return;
			}
//			popAppWin(global_obj.data.developer.user_app_numbers,global_obj.data.developer.user_app_limit); 
			if (userInfo.user_app_numbers < userInfo.user_app_limit) {
				location.href = "/apps/add/4";
			}
		}
	});