global_obj.data.navPos = "3";
tpl.websites_web = [
'<!--{ include file="header.tpl" }-->',
	tpl.header,
'<link href="http://mat1.gtimg.com/app/opent/css/developer/index/developer.css" rel="stylesheet" type="text/css"/>',
'<div class="wrapper developer_web">',
	'<h1>网页应用</h1>',
	'<p>通过调用腾讯微博API接口方式，在网站中创建web应用；</p>',
	'<p>在第三方网页内访问使用，可使用分享到微博功能；</p>',
	'<p>增强网站微博用户互动性，并通过分享行为为网站带来回流。</p>',
	'<div class="developer_mask">',
		'<a href="/developer/insite/" title="站内应用" class="developer_mask_link">站内应用&gt;</a>',
	'</div>',
	'<a href="javascript:void();" title="创建应用" class="developer_newapp"></a>',
'</div>',
'<div class="wrapper developer_interfix">',
	'<div class="developer_doc">',
		'<h3 class="developer_subtit">文档说明</h3>',
		'<ul class="developer_doc_list doc_icons_web">',
			'<li class="developer_doc_li developer_doc_li1">',
				'<h4><a href="http://wiki.open.t.qq.com/index.php/%E5%BA%94%E7%94%A8%E6%8E%A5%E5%85%A5%E6%8C%87%E5%BC%95" target="_blank">接入指引</a></h4>',
				'<p>从创建应用到应用通过审核的流程介绍</p>',
			'</li>',
			'<li class="developer_doc_li developer_doc_li2">',
				'<h4><a href="http://wiki.open.t.qq.com/index.php/API%E6%96%87%E6%A1%A3" target="_blank">API文档</a></h4>',
				'<p>API接口描述及说明文档</p>',
			'</li>',
			'<li class="developer_doc_li developer_doc_li3">',
				'<h4><a href="http://wiki.open.t.qq.com/index.php/%E8%85%BE%E8%AE%AF%E5%BE%AE%E5%8D%9A%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0%E7%AC%AC%E4%B8%89%E6%96%B9%E5%BA%94%E7%94%A8%E5%AE%A1%E6%A0%B8%E8%A7%84%E8%8C%83" target="_blank">审核规范</a></h4>',
				'<p>腾讯微博开放平台第三方应用审核规范</p>',
			'</li>',
			'<li class="developer_doc_li developer_doc_li4">',
				'<h4><a href="http://wiki.open.t.qq.com/index.php/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94" target="_blank">常见问题</a></h4>',
				'<p>为开发者提供产品、技术方面常见问题解答</p>',
			'</li>',
		'</ul>',
	'</div>',
	'<div class="developer_apps">',
		'<h3 class="developer_subtit">成功案例</h3>',
		'<ul class="developer_applist">',
			'<li class="demo_app">',
				'<a target="_blank" href="http://app.t.qq.com/app/intro/170037?via=170037_WB.MYAPPS.1.14" class="demo_app_icon">',
					'<img src="http://openmat.gtimg.com/pic/170037_50.png" class="demo_app_icon_img"/>',
				'</a>',
				'<h3>',
					'<a target="_blank" href="http://app.t.qq.com/app/intro/170037?via=170037_WB.MYAPPS.1.14" title="fawave">fawave</a>',
				'</h3>',
			'</li>',
			'<li class="demo_app">',
				'<a target="_blank" href="http://app.t.qq.com/app/intro/801047770?via=801047770_WB.MYAPPS.1.14" class="demo_app_icon">',
					'<img src="http://openmat.gtimg.com/pic/801047770_50.png" class="demo_app_icon_img"/>',
				'</a>',
				'<h3>',
					'<a target="_blank" href="http://app.t.qq.com/app/intro/801047770?via=801047770_WB.MYAPPS.1.14" title="转发抽奖平台">转发抽奖平台</a>',
				'</h3>',
			'</li>',
			'<li class="demo_app">',
				'<a target="_blank" href="http://app.t.qq.com/app/intro/170043?via=170043_WB.MYAPPS.1.14" class="demo_app_icon">',
					'<img src="http://openmat.gtimg.com/pic/170043_50.png" class="demo_app_icon_img"/>',
				'</a>',
				'<h3>',
					'<a target="_blank" href="http://app.t.qq.com/app/intro/170043?via=170043_WB.MYAPPS.1.14" title="百度搜索框">百度搜索框</a>',
				'</h3>',
			'</li>',
			'<li class="demo_app">',
				'<a target="_blank" href="http://app.t.qq.com/app/intro/801019227?via=801019227_WB.MYAPPS.1.14" class="demo_app_icon">',
					'<img src="http://openmat.gtimg.com/pic/801019227_50.png" class="demo_app_icon_img"/>',
				'</a>',
				'<h3>',
					'<a target="_blank" href="http://app.t.qq.com/app/intro/801019227?via=801019227_WB.MYAPPS.1.14" title="周伯通招聘">周伯通招聘</a>',
				'</h3>',
			'</li>',
			'<li class="demo_app">',
				'<a target="_blank" href="http://app.t.qq.com/app/intro/170164?via=170164_WB.MYAPPS.1.14" class="demo_app_icon">',
					'<img src="http://openmat.gtimg.com/pic/170164_50.png" class="demo_app_icon_img"/>',
				'</a>',
				'<h3>',
					'<a target="_blank" href="http://app.t.qq.com/app/intro/170164?via=170164_WB.MYAPPS.1.14" title="微帮">微帮</a>',
				'</h3>',
			'</li>',
			'<li class="demo_app">',
				'<a target="_blank" href="http://app.t.qq.com/app/intro/801088570?via=801088570_WB.MYAPPS.1.14" class="demo_app_icon">',
					'<img src="http://openmat.gtimg.com/pic/801088570_50.png" class="demo_app_icon_img"/>',
				'</a>',
				'<h3>',
					'<a target="_blank" href="http://app.t.qq.com/app/intro/801088570?via=801088570_WB.MYAPPS.1.14" title="我的人脉地图">我的人脉地图</a>',
				'</h3>',
			'</li>',
			'<li class="demo_app">',
				'<a target="_blank" href="http://app.t.qq.com/app/intro/170211?via=170211_WB.MYAPPS.1.14" class="demo_app_icon">',
					'<img src="http://openmat.gtimg.com/pic/170211_50.png" class="demo_app_icon_img"/>',
				'</a>',
				'<h3>',
					'<a target="_blank" href="http://app.t.qq.com/app/intro/170211?via=170211_WB.MYAPPS.1.14" title="微派">微派</a>',
				'</h3>',
			'</li>',
			'<li class="demo_app">',
				'<a target="_blank" href="http://app.t.qq.com/app/intro/801068220?via=801068220_WB.MYAPPS.1.14" class="demo_app_icon">',
					'<img src="http://openmat.gtimg.com/pic/801068220_50.png" class="demo_app_icon_img"/>',
				'</a>',
				'<h3>',
					'<a target="_blank" href="http://app.t.qq.com/app/intro/801068220?via=801068220_WB.MYAPPS.1.14" title="穿衣选衣看性格">穿衣选衣看性格</a>',
				'</h3>',
			'</li>',
		'</ul>',
	'</div>',
'</div>',
'<!--{ include file="footer.tpl" }-->',
		tpl.footer
	].join("");

	$('#main').html(tmpl(tpl.websites_web,global_obj.data));
	window.init();
	util.setLoginInfo();
	
	$(".developer_newapp").click(function(){
		if( hdlogin==undefined || hdlogin == false || hdlogin == 'false' ){
				return checkuserLogin(encodeURIComponent(location.href.replace(new RegExp(location.pathname+".*"),"/apps/add/1")));
		}else{
			if( userInfo.reg_wb == 0 ){
				location.href = "http://reg.t.qq.com/invite.php";
				return;
			}
			if (userInfo.user_app_numbers < userInfo.user_app_limit) {
				location.href = "/apps/add/1";
			}
		}
	});
