this.tpl = this.tpl||{};
this.tpl.wireless_intro = [
this.tpl.header,
'<link href="http://mat1.gtimg.com/app/opent/css/wireless/wireless.css" rel="stylesheet" type="text/css"/>',
'<div class="wrapper breadcast">',
'</div>',
'<div id="content" class="wrapper main main_comp w_intromain">',
    '<h1 class="introtit">无线应用接入介绍</h1>',
    '<div class="w_introdiv1">',
        '<p>无线应用接入开放平台为第三方开发者提供了更为简便的合作模式，接入平台的手机端及平板电脑端应用，可以让用户只需要使用微博账号密码或QQ账号密码即可登录，简化用户注册流程，同时可借助微博的关系链基础，增进用户与好友间的交互，提升使用体验</p>',
        '<p>为了更好的帮助第三方接入移动应用，微博移动应用开放平台提供了支持iOS、Android及Windows Phone7的SDK，封装了微博登录及部分微博开放API接口，应用只需要修改相应参数，不需要理解验证授权流程，即可实现微博登录功能。</p>',
    '</div>',
    '<h2 class="comp_sub_tit">接入流程</h2>',
    '<div class="w_introdiv2">',
        '<img src="http://mat1.gtimg.com/app/opent/images/wireless/w_introstep.jpg"/>',
        '<div class="w_introdiv3">',
            '<div class="w_introstep">第一步：成为开发者</div>',
            '<p>首先需要注册开发，如果您已经是开发者，请跳过此步骤。</p>',
            '<p>注册开发者：<a href="http://dev.t.qq.com/developer/bedever" target="_blank">http://dev.t.qq.com/developer/bedever</a></p>',
        '</div>',
        '<div class="w_introdiv3">',
            '<div class="w_introstep">第二步：创建应用</div>',
            '<p>首先开发者需要在<a href="http://dev.t.qq.com/apps/add/6" target="_blank">http://dev.t.qq.com/apps/add/6</a>创建->无线应用</p>',
            '<img src="http://mat1.gtimg.com/app/opent/images/wireless/w_introstep2.jpg" />',
        '</div>',
        '<div class="w_introdiv3">',
            '<div class="w_introstep">第三步：填写应用信息</div>',
            '<p>完善应用信息，红色部分为必填项</p>',
            '<img src="http://mat1.gtimg.com/app/opent/images/wireless/w_introstep3.jpg" />',
        '</div>',
        '<div class="w_introdiv3">',
            '<div class="w_introstep">第四步：获取appkey 和 App Secret</div>',
            '<img src="http://mat1.gtimg.com/app/opent/images/wireless/w_introstep4.jpg" />',
        '</div>',
        '<div class="w_introdiv3">',
            '<div class="w_introstep">第五步：开发应用</div>',
            '<p>当您成功申请到AppKey和AppSecret后，您就可以调用腾讯微博开放平台上的一系列接口了或者下载相应的SDK开发您的应用了。</p>',
            '<p>详细接口文档请参考：<a href="http://wiki.open.t.qq.com/index.php/API%E6%96%87%E6%A1%A3" target="_blank">API文档</a>      SDK下载地体：<a href="http://wiki.open.t.qq.com/index.php/SDK%E4%B8%8B%E8%BD%BD" target="_blank">SDK下载</a></p>',
        '</div>',
    '</div>',
'</div>',
this.tpl.footer
].join("");
